"""rename user columns and remove duplicate index

Revision ID: 33ef22aa4c87
Revises: 49ba933d353f
Create Date: 2026-05-02 22:29:35.870643

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "33ef22aa4c87"
down_revision: Union[str, Sequence[str], None] = "49ba933d353f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "hash_password", new_column_name="hashed_password")
    op.alter_column("user", "update_at", new_column_name="updated_at")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
   
    op.alter_column("user", "updated_at", new_column_name="update_at")
    op.alter_column("user", "hashed_password", new_column_name="hash_password")
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    # ### end Alembic commands ###
